# Generated by Django 3.0.5 on 2020-05-01 20:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=9)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=150)),
                ('telefono', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.CharField(max_length=1000)),
                ('inicio', models.DateField(default=datetime.date.today)),
                ('fin', models.DateField(default=datetime.date.today)),
                ('presupuesto', models.CharField(max_length=150)),
                ('cliente', models.CharField(max_length=150)),
                ('empleados', models.ManyToManyField(to='appEmpresaDjango.Empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.CharField(max_length=1000)),
                ('inicio', models.DateField(default=datetime.date.today)),
                ('fin', models.DateField(default=datetime.date.today)),
                ('prioridad', models.CharField(max_length=150)),
                ('estado', models.CharField(max_length=150)),
                ('notas', models.CharField(max_length=150)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appEmpresaDjango.Proyecto')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appEmpresaDjango.Empleado')),
            ],
        ),
    ]
