# Generated by Django 3.0.5 on 2020-04-29 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appEmpresaDjango', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='empleados',
        ),
        migrations.AddField(
            model_name='proyecto',
            name='empleados',
            field=models.ManyToManyField(to='appEmpresaDjango.Empleado'),
        ),
    ]
